FORMAT: 1A
HOST: https://bouncio-core.herokuapp.com/

# Bouncio

Handles authentication

## Users Collection [/users]

### List All Users [GET]

+ Response 200 (application/json; charset=utf-8)

        {
            "data": [
                {
                    "type": "users",
                    "id": "896ad747-442e-4438-aee5-b85cf234a40b",
                    "attributes": {
                        "email": "kurt@example.com"
                    }
                }
            ]
        }

### Create a user [POST]

You may register for an account using this endpoint

+ Request (application/json; charset=utf-8)

        {
            "user": {
              "email": "kurt@example.com",
              "password": "12345678"
            }
        }

+ Response 201 (application/json; charset=utf-8)

    + Body

            {
                "data": {
                    "type": "users",
                    "id": "896ad747-442e-4438-aee5-b85cf234a40b",
                    "attributes": {
                        "email": "kurt@example.com"
                    }
                }
            }
